package org.gedcom7.parser.validation;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

/**
 * GEDCOM 7 structure definition lookup tables derived from the official
 * specification TSV files (cardinalities.tsv, substructures.tsv).
 *
 * <p>This class can be regenerated by running:
 * {@code ./gradlew generateStructureDefinitions} and copying the output
 * over this file.
 *
 * <p>Provides HashMap-based lookups for resolving structure context
 * and cardinality constraints with O(1) average performance.
 */
public final class StructureDefinitions {

    private StructureDefinitions() {}

    // ─── Substructure lookup: (parentId\ttag) -> childStructureId ───

    private static final Map<String, String> SUB_LOOKUP;
    static {
        Map<String, String> m = new HashMap<>(512);
        // record-INDI substructures
        m.put("record-INDI\tNAME", "INDI-NAME");
        m.put("record-INDI\tSEX", "SEX");
        m.put("record-INDI\tBIRT", "BIRT");
        m.put("record-INDI\tDEAT", "DEAT");
        m.put("record-INDI\tADOP", "ADOP");
        m.put("record-INDI\tBAPM", "BAPM");
        m.put("record-INDI\tBARM", "BARM");
        m.put("record-INDI\tBASM", "BASM");
        m.put("record-INDI\tBLES", "BLES");
        m.put("record-INDI\tBURI", "BURI");
        m.put("record-INDI\tCAST", "CAST");
        m.put("record-INDI\tCENS", "INDI-CENS");
        m.put("record-INDI\tCHR", "CHR");
        m.put("record-INDI\tCHRA", "CHRA");
        m.put("record-INDI\tCONF", "CONF");
        m.put("record-INDI\tCONL", "CONL");
        m.put("record-INDI\tCREM", "CREM");
        m.put("record-INDI\tDSCR", "DSCR");
        m.put("record-INDI\tEDUC", "EDUC");
        m.put("record-INDI\tEMIG", "EMIG");
        m.put("record-INDI\tENDL", "ENDL");
        m.put("record-INDI\tEVEN", "INDI-EVEN");
        m.put("record-INDI\tFACT", "INDI-FACT");
        m.put("record-INDI\tFAMC", "INDI-FAMC");
        m.put("record-INDI\tFAMS", "FAMS");
        m.put("record-INDI\tFCOM", "FCOM");
        m.put("record-INDI\tGRAD", "GRAD");
        m.put("record-INDI\tIDNO", "IDNO");
        m.put("record-INDI\tIMMI", "IMMI");
        m.put("record-INDI\tINIL", "INIL");
        m.put("record-INDI\tNATI", "NATI");
        m.put("record-INDI\tNATU", "NATU");
        m.put("record-INDI\tNCHI", "INDI-NCHI");
        m.put("record-INDI\tNMR", "NMR");
        m.put("record-INDI\tNO", "NO");
        m.put("record-INDI\tNOTE", "NOTE");
        m.put("record-INDI\tOBJE", "OBJE");
        m.put("record-INDI\tOCCU", "OCCU");
        m.put("record-INDI\tORDN", "ORDN");
        m.put("record-INDI\tPROB", "PROB");
        m.put("record-INDI\tPROP", "PROP");
        m.put("record-INDI\tREFN", "REFN");
        m.put("record-INDI\tRELI", "INDI-RELI");
        m.put("record-INDI\tRESI", "INDI-RESI");
        m.put("record-INDI\tRESN", "RESN");
        m.put("record-INDI\tRETI", "RETI");
        m.put("record-INDI\tSLGC", "SLGC");
        m.put("record-INDI\tSNOTE", "SNOTE");
        m.put("record-INDI\tSOUR", "SOUR");
        m.put("record-INDI\tSSN", "SSN");
        m.put("record-INDI\tSUBM", "SUBM");
        m.put("record-INDI\tTITL", "INDI-TITL");
        m.put("record-INDI\tUID", "UID");
        m.put("record-INDI\tWILL", "WILL");
        m.put("record-INDI\tALIA", "ALIA");
        m.put("record-INDI\tANCI", "ANCI");
        m.put("record-INDI\tASSO", "ASSO");
        m.put("record-INDI\tBAPL", "BAPL");
        m.put("record-INDI\tCHAN", "CHAN");
        m.put("record-INDI\tCREA", "CREA");
        m.put("record-INDI\tDESI", "DESI");
        m.put("record-INDI\tEXID", "EXID");

        // record-FAM substructures
        m.put("record-FAM\tHUSB", "FAM-HUSB");
        m.put("record-FAM\tWIFE", "FAM-WIFE");
        m.put("record-FAM\tCHIL", "CHIL");
        m.put("record-FAM\tMARR", "MARR");
        m.put("record-FAM\tMARB", "MARB");
        m.put("record-FAM\tMARC", "MARC");
        m.put("record-FAM\tMARL", "MARL");
        m.put("record-FAM\tMARS", "MARS");
        m.put("record-FAM\tANUL", "ANUL");
        m.put("record-FAM\tDIV", "DIV");
        m.put("record-FAM\tDIVF", "DIVF");
        m.put("record-FAM\tENGA", "ENGA");
        m.put("record-FAM\tCENS", "FAM-CENS");
        m.put("record-FAM\tEVEN", "FAM-EVEN");
        m.put("record-FAM\tFACT", "FAM-FACT");
        m.put("record-FAM\tNCHI", "FAM-NCHI");
        m.put("record-FAM\tRESI", "FAM-RESI");
        m.put("record-FAM\tNO", "NO");
        m.put("record-FAM\tNOTE", "NOTE");
        m.put("record-FAM\tOBJE", "OBJE");
        m.put("record-FAM\tREFN", "REFN");
        m.put("record-FAM\tRESN", "RESN");
        m.put("record-FAM\tSLGS", "SLGS");
        m.put("record-FAM\tSNOTE", "SNOTE");
        m.put("record-FAM\tSOUR", "SOUR");
        m.put("record-FAM\tSUBM", "SUBM");
        m.put("record-FAM\tUID", "UID");
        m.put("record-FAM\tASSO", "ASSO");
        m.put("record-FAM\tCHAN", "CHAN");
        m.put("record-FAM\tCREA", "CREA");
        m.put("record-FAM\tEXID", "EXID");

        // record-SOUR substructures
        m.put("record-SOUR\tABBR", "ABBR");
        m.put("record-SOUR\tAUTH", "AUTH");
        m.put("record-SOUR\tDATA", "DATA");
        m.put("record-SOUR\tNOTE", "NOTE");
        m.put("record-SOUR\tOBJE", "OBJE");
        m.put("record-SOUR\tPUBL", "PUBL");
        m.put("record-SOUR\tREFN", "REFN");
        m.put("record-SOUR\tREPO", "REPO");
        m.put("record-SOUR\tTEXT", "TEXT");
        m.put("record-SOUR\tTITL", "TITL");
        m.put("record-SOUR\tUID", "UID");
        m.put("record-SOUR\tCHAN", "CHAN");
        m.put("record-SOUR\tCREA", "CREA");
        m.put("record-SOUR\tEXID", "EXID");
        m.put("record-SOUR\tSNOTE", "SNOTE");

        // record-REPO substructures
        m.put("record-REPO\tNAME", "NAME");
        m.put("record-REPO\tADDR", "ADDR");
        m.put("record-REPO\tNOTE", "NOTE");
        m.put("record-REPO\tREFN", "REFN");
        m.put("record-REPO\tSNOTE", "SNOTE");
        m.put("record-REPO\tUID", "UID");
        m.put("record-REPO\tCHAN", "CHAN");
        m.put("record-REPO\tCREA", "CREA");
        m.put("record-REPO\tEXID", "EXID");
        m.put("record-REPO\tEMAIL", "EMAIL");
        m.put("record-REPO\tFAX", "FAX");
        m.put("record-REPO\tPHON", "PHON");
        m.put("record-REPO\tWWW", "WWW");

        // record-OBJE substructures
        m.put("record-OBJE\tFILE", "FILE");
        m.put("record-OBJE\tNOTE", "NOTE");
        m.put("record-OBJE\tREFN", "REFN");
        m.put("record-OBJE\tRESN", "RESN");
        m.put("record-OBJE\tSNOTE", "SNOTE");
        m.put("record-OBJE\tSOUR", "SOUR");
        m.put("record-OBJE\tUID", "UID");
        m.put("record-OBJE\tCHAN", "CHAN");
        m.put("record-OBJE\tCREA", "CREA");
        m.put("record-OBJE\tEXID", "EXID");

        // record-SNOTE substructures
        m.put("record-SNOTE\tLANG", "LANG");
        m.put("record-SNOTE\tMIME", "MIME");
        m.put("record-SNOTE\tREFN", "REFN");
        m.put("record-SNOTE\tSOUR", "SOUR");
        m.put("record-SNOTE\tTRAN", "NOTE-TRAN");
        m.put("record-SNOTE\tUID", "UID");
        m.put("record-SNOTE\tCHAN", "CHAN");
        m.put("record-SNOTE\tCREA", "CREA");
        m.put("record-SNOTE\tEXID", "EXID");

        // record-SUBM substructures
        m.put("record-SUBM\tNAME", "NAME");
        m.put("record-SUBM\tADDR", "ADDR");
        m.put("record-SUBM\tLANG", "SUBM-LANG");
        m.put("record-SUBM\tNOTE", "NOTE");
        m.put("record-SUBM\tOBJE", "OBJE");
        m.put("record-SUBM\tREFN", "REFN");
        m.put("record-SUBM\tSNOTE", "SNOTE");
        m.put("record-SUBM\tUID", "UID");
        m.put("record-SUBM\tCHAN", "CHAN");
        m.put("record-SUBM\tCREA", "CREA");
        m.put("record-SUBM\tEXID", "EXID");
        m.put("record-SUBM\tEMAIL", "EMAIL");
        m.put("record-SUBM\tFAX", "FAX");
        m.put("record-SUBM\tPHON", "PHON");
        m.put("record-SUBM\tWWW", "WWW");

        // HEAD substructures
        m.put("HEAD\tCOPR", "COPR");
        m.put("HEAD\tDATE", "HEAD-DATE");
        m.put("HEAD\tDEST", "DEST");
        m.put("HEAD\tGEDC", "GEDC");
        m.put("HEAD\tLANG", "HEAD-LANG");
        m.put("HEAD\tNOTE", "NOTE");
        m.put("HEAD\tPLAC", "HEAD-PLAC");
        m.put("HEAD\tSCHMA", "SCHMA");
        m.put("HEAD\tSNOTE", "SNOTE");
        m.put("HEAD\tSOUR", "HEAD-SOUR");
        m.put("HEAD\tSUBM", "SUBM");

        // GEDC substructures
        m.put("GEDC\tVERS", "GEDC-VERS");

        // HEAD-SOUR substructures
        m.put("HEAD-SOUR\tCORP", "CORP");
        m.put("HEAD-SOUR\tDATA", "HEAD-SOUR-DATA");
        m.put("HEAD-SOUR\tNAME", "NAME");
        m.put("HEAD-SOUR\tVERS", "VERS");

        // HEAD-SOUR-DATA substructures
        m.put("HEAD-SOUR-DATA\tCOPR", "COPR");
        m.put("HEAD-SOUR-DATA\tDATE", "DATE-exact");

        // HEAD-PLAC substructures
        m.put("HEAD-PLAC\tFORM", "HEAD-PLAC-FORM");

        // HEAD-DATE substructures
        m.put("HEAD-DATE\tTIME", "TIME");

        // SCHMA substructures
        m.put("SCHMA\tTAG", "TAG");

        // INDI-NAME substructures
        m.put("INDI-NAME\tGIVN", "GIVN");
        m.put("INDI-NAME\tNICK", "NICK");
        m.put("INDI-NAME\tNPFX", "NPFX");
        m.put("INDI-NAME\tNSFX", "NSFX");
        m.put("INDI-NAME\tNOTE", "NOTE");
        m.put("INDI-NAME\tSNOTE", "SNOTE");
        m.put("INDI-NAME\tSOUR", "SOUR");
        m.put("INDI-NAME\tSPFX", "SPFX");
        m.put("INDI-NAME\tSURN", "SURN");
        m.put("INDI-NAME\tTRAN", "NAME-TRAN");
        m.put("INDI-NAME\tTYPE", "NAME-TYPE");

        // BIRT substructures
        m.put("BIRT\tADDR", "ADDR");
        m.put("BIRT\tAGE", "AGE");
        m.put("BIRT\tAGNC", "AGNC");
        m.put("BIRT\tASSO", "ASSO");
        m.put("BIRT\tCAUS", "CAUS");
        m.put("BIRT\tDATE", "DATE");
        m.put("BIRT\tFAMC", "FAMC");
        m.put("BIRT\tNOTE", "NOTE");
        m.put("BIRT\tOBJE", "OBJE");
        m.put("BIRT\tPHON", "PHON");
        m.put("BIRT\tPLAC", "PLAC");
        m.put("BIRT\tRELI", "RELI");
        m.put("BIRT\tRESN", "RESN");
        m.put("BIRT\tSDATE", "SDATE");
        m.put("BIRT\tSNOTE", "SNOTE");
        m.put("BIRT\tSOUR", "SOUR");
        m.put("BIRT\tTYPE", "TYPE");
        m.put("BIRT\tUID", "UID");

        // DEAT substructures
        m.put("DEAT\tADDR", "ADDR");
        m.put("DEAT\tAGE", "AGE");
        m.put("DEAT\tAGNC", "AGNC");
        m.put("DEAT\tASSO", "ASSO");
        m.put("DEAT\tCAUS", "CAUS");
        m.put("DEAT\tDATE", "DATE");
        m.put("DEAT\tNOTE", "NOTE");
        m.put("DEAT\tOBJE", "OBJE");
        m.put("DEAT\tPHON", "PHON");
        m.put("DEAT\tPLAC", "PLAC");
        m.put("DEAT\tRELI", "RELI");
        m.put("DEAT\tRESN", "RESN");
        m.put("DEAT\tSDATE", "SDATE");
        m.put("DEAT\tSNOTE", "SNOTE");
        m.put("DEAT\tSOUR", "SOUR");
        m.put("DEAT\tTYPE", "TYPE");
        m.put("DEAT\tUID", "UID");

        // MARR substructures
        m.put("MARR\tADDR", "ADDR");
        m.put("MARR\tAGNC", "AGNC");
        m.put("MARR\tASSO", "ASSO");
        m.put("MARR\tCAUS", "CAUS");
        m.put("MARR\tDATE", "DATE");
        m.put("MARR\tHUSB", "HUSB");
        m.put("MARR\tNOTE", "NOTE");
        m.put("MARR\tOBJE", "OBJE");
        m.put("MARR\tPHON", "PHON");
        m.put("MARR\tPLAC", "PLAC");
        m.put("MARR\tRELI", "RELI");
        m.put("MARR\tRESN", "RESN");
        m.put("MARR\tSDATE", "SDATE");
        m.put("MARR\tSNOTE", "SNOTE");
        m.put("MARR\tSOUR", "SOUR");
        m.put("MARR\tTYPE", "TYPE");
        m.put("MARR\tUID", "UID");
        m.put("MARR\tWIFE", "WIFE");

        // ADDR substructures
        m.put("ADDR\tADR1", "ADR1");
        m.put("ADDR\tADR2", "ADR2");
        m.put("ADDR\tADR3", "ADR3");
        m.put("ADDR\tCITY", "CITY");
        m.put("ADDR\tCTRY", "CTRY");
        m.put("ADDR\tPOST", "POST");
        m.put("ADDR\tSTAE", "STAE");

        // PLAC substructures
        m.put("PLAC\tEXID", "EXID");
        m.put("PLAC\tFORM", "PLAC-FORM");
        m.put("PLAC\tLANG", "LANG");
        m.put("PLAC\tMAP", "MAP");
        m.put("PLAC\tNOTE", "NOTE");
        m.put("PLAC\tSNOTE", "SNOTE");
        m.put("PLAC\tTRAN", "PLAC-TRAN");

        // MAP substructures
        m.put("MAP\tLATI", "LATI");
        m.put("MAP\tLONG", "LONG");

        // DATE substructures
        m.put("DATE\tPHRASE", "PHRASE");
        m.put("DATE\tTIME", "TIME");

        // SOUR (citation) substructures
        m.put("SOUR\tDATA", "SOUR-DATA");
        m.put("SOUR\tEVEN", "SOUR-EVEN");
        m.put("SOUR\tNOTE", "NOTE");
        m.put("SOUR\tOBJE", "OBJE");
        m.put("SOUR\tPAGE", "PAGE");
        m.put("SOUR\tQUAY", "QUAY");
        m.put("SOUR\tSNOTE", "SNOTE");

        // CHAN substructures
        m.put("CHAN\tDATE", "DATE-exact");
        m.put("CHAN\tNOTE", "NOTE");
        m.put("CHAN\tSNOTE", "SNOTE");

        // CREA substructures
        m.put("CREA\tDATE", "DATE-exact");

        // FILE substructures
        m.put("FILE\tFORM", "FORM");
        m.put("FILE\tTITL", "TITL");
        m.put("FILE\tTRAN", "FILE-TRAN");

        // FORM substructures
        m.put("FORM\tMEDI", "MEDI");

        // REFN substructures
        m.put("REFN\tTYPE", "TYPE");

        // REPO (citation) substructures
        m.put("REPO\tCALN", "CALN");
        m.put("REPO\tNOTE", "NOTE");
        m.put("REPO\tSNOTE", "SNOTE");

        // ASSO substructures
        m.put("ASSO\tNOTE", "NOTE");
        m.put("ASSO\tPHRASE", "PHRASE");
        m.put("ASSO\tROLE", "ROLE");
        m.put("ASSO\tSNOTE", "SNOTE");
        m.put("ASSO\tSOUR", "SOUR");

        // FAMS substructures
        m.put("FAMS\tNOTE", "NOTE");
        m.put("FAMS\tSNOTE", "SNOTE");

        // INDI-FAMC substructures
        m.put("INDI-FAMC\tNOTE", "NOTE");
        m.put("INDI-FAMC\tPEDI", "PEDI");
        m.put("INDI-FAMC\tSNOTE", "SNOTE");
        m.put("INDI-FAMC\tSTAT", "FAMC-STAT");

        // NOTE substructures
        m.put("NOTE\tLANG", "LANG");
        m.put("NOTE\tMIME", "MIME");
        m.put("NOTE\tSOUR", "SOUR");
        m.put("NOTE\tTRAN", "NOTE-TRAN");

        // NO substructures
        m.put("NO\tDATE", "NO-DATE");
        m.put("NO\tNOTE", "NOTE");
        m.put("NO\tSNOTE", "SNOTE");
        m.put("NO\tSOUR", "SOUR");

        // FAM-HUSB / FAM-WIFE substructures
        m.put("FAM-HUSB\tPHRASE", "PHRASE");
        m.put("FAM-WIFE\tPHRASE", "PHRASE");

        // ADOP substructures
        m.put("ADOP\tFAMC", "ADOP-FAMC");
        m.put("ADOP-FAMC\tADOP", "FAMC-ADOP");

        // EXID substructures
        m.put("EXID\tTYPE", "EXID-TYPE");

        SUB_LOOKUP = Collections.unmodifiableMap(m);
    }

    // ─── Cardinality lookup: (parentId\tchildStructureId) -> cardinality ─

    private static final Map<String, String> CARD_LOOKUP;
    static {
        Map<String, String> m = new HashMap<>(512);

        // record-INDI cardinalities
        m.put("record-INDI\tINDI-NAME", "{0:M}");
        m.put("record-INDI\tSEX", "{0:1}");
        m.put("record-INDI\tBIRT", "{0:M}");
        m.put("record-INDI\tDEAT", "{0:M}");
        m.put("record-INDI\tADOP", "{0:M}");
        m.put("record-INDI\tBAPM", "{0:M}");
        m.put("record-INDI\tBARM", "{0:M}");
        m.put("record-INDI\tBASM", "{0:M}");
        m.put("record-INDI\tBLES", "{0:M}");
        m.put("record-INDI\tBURI", "{0:M}");
        m.put("record-INDI\tCAST", "{0:M}");
        m.put("record-INDI\tINDI-CENS", "{0:M}");
        m.put("record-INDI\tCHR", "{0:M}");
        m.put("record-INDI\tCHRA", "{0:M}");
        m.put("record-INDI\tCONF", "{0:M}");
        m.put("record-INDI\tCONL", "{0:M}");
        m.put("record-INDI\tCREM", "{0:M}");
        m.put("record-INDI\tDSCR", "{0:M}");
        m.put("record-INDI\tEDUC", "{0:M}");
        m.put("record-INDI\tEMIG", "{0:M}");
        m.put("record-INDI\tENDL", "{0:M}");
        m.put("record-INDI\tINDI-EVEN", "{0:M}");
        m.put("record-INDI\tINDI-FACT", "{0:M}");
        m.put("record-INDI\tINDI-FAMC", "{0:M}");
        m.put("record-INDI\tFAMS", "{0:M}");
        m.put("record-INDI\tFCOM", "{0:M}");
        m.put("record-INDI\tGRAD", "{0:M}");
        m.put("record-INDI\tIDNO", "{0:M}");
        m.put("record-INDI\tIMMI", "{0:M}");
        m.put("record-INDI\tINIL", "{0:M}");
        m.put("record-INDI\tNATI", "{0:M}");
        m.put("record-INDI\tNATU", "{0:M}");
        m.put("record-INDI\tINDI-NCHI", "{0:M}");
        m.put("record-INDI\tNMR", "{0:M}");
        m.put("record-INDI\tNO", "{0:M}");
        m.put("record-INDI\tNOTE", "{0:M}");
        m.put("record-INDI\tOBJE", "{0:M}");
        m.put("record-INDI\tOCCU", "{0:M}");
        m.put("record-INDI\tORDN", "{0:M}");
        m.put("record-INDI\tPROB", "{0:M}");
        m.put("record-INDI\tPROP", "{0:M}");
        m.put("record-INDI\tREFN", "{0:M}");
        m.put("record-INDI\tINDI-RELI", "{0:M}");
        m.put("record-INDI\tINDI-RESI", "{0:M}");
        m.put("record-INDI\tRESN", "{0:1}");
        m.put("record-INDI\tRETI", "{0:M}");
        m.put("record-INDI\tSLGC", "{0:M}");
        m.put("record-INDI\tSNOTE", "{0:M}");
        m.put("record-INDI\tSOUR", "{0:M}");
        m.put("record-INDI\tSSN", "{0:M}");
        m.put("record-INDI\tSUBM", "{0:M}");
        m.put("record-INDI\tINDI-TITL", "{0:M}");
        m.put("record-INDI\tUID", "{0:M}");
        m.put("record-INDI\tWILL", "{0:M}");
        m.put("record-INDI\tALIA", "{0:M}");
        m.put("record-INDI\tANCI", "{0:M}");
        m.put("record-INDI\tASSO", "{0:M}");
        m.put("record-INDI\tBAPL", "{0:M}");
        m.put("record-INDI\tCHAN", "{0:1}");
        m.put("record-INDI\tCREA", "{0:1}");
        m.put("record-INDI\tDESI", "{0:M}");
        m.put("record-INDI\tEXID", "{0:M}");

        // record-FAM cardinalities
        m.put("record-FAM\tFAM-HUSB", "{0:1}");
        m.put("record-FAM\tFAM-WIFE", "{0:1}");
        m.put("record-FAM\tCHIL", "{0:M}");
        m.put("record-FAM\tMARR", "{0:M}");
        m.put("record-FAM\tMARB", "{0:M}");
        m.put("record-FAM\tMARC", "{0:M}");
        m.put("record-FAM\tMARL", "{0:M}");
        m.put("record-FAM\tMARS", "{0:M}");
        m.put("record-FAM\tANUL", "{0:M}");
        m.put("record-FAM\tDIV", "{0:M}");
        m.put("record-FAM\tDIVF", "{0:M}");
        m.put("record-FAM\tENGA", "{0:M}");
        m.put("record-FAM\tFAM-CENS", "{0:M}");
        m.put("record-FAM\tFAM-EVEN", "{0:M}");
        m.put("record-FAM\tFAM-FACT", "{0:M}");
        m.put("record-FAM\tFAM-NCHI", "{0:M}");
        m.put("record-FAM\tFAM-RESI", "{0:M}");
        m.put("record-FAM\tNO", "{0:M}");
        m.put("record-FAM\tNOTE", "{0:M}");
        m.put("record-FAM\tOBJE", "{0:M}");
        m.put("record-FAM\tREFN", "{0:M}");
        m.put("record-FAM\tRESN", "{0:1}");
        m.put("record-FAM\tSLGS", "{0:M}");
        m.put("record-FAM\tSNOTE", "{0:M}");
        m.put("record-FAM\tSOUR", "{0:M}");
        m.put("record-FAM\tSUBM", "{0:M}");
        m.put("record-FAM\tUID", "{0:M}");
        m.put("record-FAM\tASSO", "{0:M}");
        m.put("record-FAM\tCHAN", "{0:1}");
        m.put("record-FAM\tCREA", "{0:1}");
        m.put("record-FAM\tEXID", "{0:M}");

        // record-SOUR cardinalities
        m.put("record-SOUR\tABBR", "{0:1}");
        m.put("record-SOUR\tAUTH", "{0:1}");
        m.put("record-SOUR\tDATA", "{0:1}");
        m.put("record-SOUR\tNOTE", "{0:M}");
        m.put("record-SOUR\tOBJE", "{0:M}");
        m.put("record-SOUR\tPUBL", "{0:1}");
        m.put("record-SOUR\tREFN", "{0:M}");
        m.put("record-SOUR\tREPO", "{0:M}");
        m.put("record-SOUR\tTEXT", "{0:1}");
        m.put("record-SOUR\tTITL", "{0:1}");
        m.put("record-SOUR\tUID", "{0:M}");
        m.put("record-SOUR\tCHAN", "{0:1}");
        m.put("record-SOUR\tCREA", "{0:1}");
        m.put("record-SOUR\tEXID", "{0:M}");
        m.put("record-SOUR\tSNOTE", "{0:M}");

        // record-REPO cardinalities
        m.put("record-REPO\tNAME", "{1:1}");
        m.put("record-REPO\tADDR", "{0:1}");
        m.put("record-REPO\tNOTE", "{0:M}");
        m.put("record-REPO\tREFN", "{0:M}");
        m.put("record-REPO\tSNOTE", "{0:M}");
        m.put("record-REPO\tUID", "{0:M}");
        m.put("record-REPO\tCHAN", "{0:1}");
        m.put("record-REPO\tCREA", "{0:1}");
        m.put("record-REPO\tEXID", "{0:M}");
        m.put("record-REPO\tEMAIL", "{0:M}");
        m.put("record-REPO\tFAX", "{0:M}");
        m.put("record-REPO\tPHON", "{0:M}");
        m.put("record-REPO\tWWW", "{0:M}");

        // record-OBJE cardinalities
        m.put("record-OBJE\tFILE", "{1:M}");
        m.put("record-OBJE\tNOTE", "{0:M}");
        m.put("record-OBJE\tREFN", "{0:M}");
        m.put("record-OBJE\tRESN", "{0:1}");
        m.put("record-OBJE\tSNOTE", "{0:M}");
        m.put("record-OBJE\tSOUR", "{0:M}");
        m.put("record-OBJE\tUID", "{0:M}");
        m.put("record-OBJE\tCHAN", "{0:1}");
        m.put("record-OBJE\tCREA", "{0:1}");
        m.put("record-OBJE\tEXID", "{0:M}");

        // record-SNOTE cardinalities
        m.put("record-SNOTE\tLANG", "{0:1}");
        m.put("record-SNOTE\tMIME", "{0:1}");
        m.put("record-SNOTE\tREFN", "{0:M}");
        m.put("record-SNOTE\tSOUR", "{0:M}");
        m.put("record-SNOTE\tNOTE-TRAN", "{0:M}");
        m.put("record-SNOTE\tUID", "{0:M}");
        m.put("record-SNOTE\tCHAN", "{0:1}");
        m.put("record-SNOTE\tCREA", "{0:1}");
        m.put("record-SNOTE\tEXID", "{0:M}");

        // record-SUBM cardinalities
        m.put("record-SUBM\tNAME", "{1:1}");
        m.put("record-SUBM\tADDR", "{0:1}");
        m.put("record-SUBM\tSUBM-LANG", "{0:M}");
        m.put("record-SUBM\tNOTE", "{0:M}");
        m.put("record-SUBM\tOBJE", "{0:M}");
        m.put("record-SUBM\tREFN", "{0:M}");
        m.put("record-SUBM\tSNOTE", "{0:M}");
        m.put("record-SUBM\tUID", "{0:M}");
        m.put("record-SUBM\tCHAN", "{0:1}");
        m.put("record-SUBM\tCREA", "{0:1}");
        m.put("record-SUBM\tEXID", "{0:M}");
        m.put("record-SUBM\tEMAIL", "{0:M}");
        m.put("record-SUBM\tFAX", "{0:M}");
        m.put("record-SUBM\tPHON", "{0:M}");
        m.put("record-SUBM\tWWW", "{0:M}");

        // HEAD cardinalities
        m.put("HEAD\tCOPR", "{0:1}");
        m.put("HEAD\tHEAD-DATE", "{0:1}");
        m.put("HEAD\tDEST", "{0:1}");
        m.put("HEAD\tGEDC", "{1:1}");
        m.put("HEAD\tHEAD-LANG", "{0:1}");
        m.put("HEAD\tNOTE", "{0:1}");
        m.put("HEAD\tHEAD-PLAC", "{0:1}");
        m.put("HEAD\tSCHMA", "{0:1}");
        m.put("HEAD\tSNOTE", "{0:1}");
        m.put("HEAD\tHEAD-SOUR", "{0:1}");
        m.put("HEAD\tSUBM", "{0:1}");

        // GEDC cardinalities
        m.put("GEDC\tGEDC-VERS", "{1:1}");

        // HEAD-SOUR cardinalities
        m.put("HEAD-SOUR\tCORP", "{0:1}");
        m.put("HEAD-SOUR\tHEAD-SOUR-DATA", "{0:1}");
        m.put("HEAD-SOUR\tNAME", "{0:1}");
        m.put("HEAD-SOUR\tVERS", "{0:1}");

        // INDI-NAME cardinalities
        m.put("INDI-NAME\tGIVN", "{0:M}");
        m.put("INDI-NAME\tNICK", "{0:M}");
        m.put("INDI-NAME\tNPFX", "{0:M}");
        m.put("INDI-NAME\tNSFX", "{0:M}");
        m.put("INDI-NAME\tNOTE", "{0:M}");
        m.put("INDI-NAME\tSNOTE", "{0:M}");
        m.put("INDI-NAME\tSOUR", "{0:M}");
        m.put("INDI-NAME\tSPFX", "{0:M}");
        m.put("INDI-NAME\tSURN", "{0:M}");
        m.put("INDI-NAME\tNAME-TRAN", "{0:M}");
        m.put("INDI-NAME\tNAME-TYPE", "{0:1}");

        // BIRT cardinalities
        m.put("BIRT\tADDR", "{0:1}");
        m.put("BIRT\tAGE", "{0:1}");
        m.put("BIRT\tAGNC", "{0:1}");
        m.put("BIRT\tASSO", "{0:M}");
        m.put("BIRT\tCAUS", "{0:1}");
        m.put("BIRT\tDATE", "{0:1}");
        m.put("BIRT\tFAMC", "{0:1}");
        m.put("BIRT\tNOTE", "{0:M}");
        m.put("BIRT\tOBJE", "{0:M}");
        m.put("BIRT\tPHON", "{0:M}");
        m.put("BIRT\tPLAC", "{0:1}");
        m.put("BIRT\tRELI", "{0:1}");
        m.put("BIRT\tRESN", "{0:1}");
        m.put("BIRT\tSDATE", "{0:1}");
        m.put("BIRT\tSNOTE", "{0:M}");
        m.put("BIRT\tSOUR", "{0:M}");
        m.put("BIRT\tTYPE", "{0:1}");
        m.put("BIRT\tUID", "{0:M}");

        // DEAT cardinalities
        m.put("DEAT\tADDR", "{0:1}");
        m.put("DEAT\tAGE", "{0:1}");
        m.put("DEAT\tAGNC", "{0:1}");
        m.put("DEAT\tASSO", "{0:M}");
        m.put("DEAT\tCAUS", "{0:1}");
        m.put("DEAT\tDATE", "{0:1}");
        m.put("DEAT\tNOTE", "{0:M}");
        m.put("DEAT\tOBJE", "{0:M}");
        m.put("DEAT\tPHON", "{0:M}");
        m.put("DEAT\tPLAC", "{0:1}");
        m.put("DEAT\tRELI", "{0:1}");
        m.put("DEAT\tRESN", "{0:1}");
        m.put("DEAT\tSDATE", "{0:1}");
        m.put("DEAT\tSNOTE", "{0:M}");
        m.put("DEAT\tSOUR", "{0:M}");
        m.put("DEAT\tTYPE", "{0:1}");
        m.put("DEAT\tUID", "{0:M}");

        // MARR cardinalities
        m.put("MARR\tADDR", "{0:1}");
        m.put("MARR\tAGNC", "{0:1}");
        m.put("MARR\tASSO", "{0:M}");
        m.put("MARR\tCAUS", "{0:1}");
        m.put("MARR\tDATE", "{0:1}");
        m.put("MARR\tHUSB", "{0:1}");
        m.put("MARR\tNOTE", "{0:M}");
        m.put("MARR\tOBJE", "{0:M}");
        m.put("MARR\tPHON", "{0:M}");
        m.put("MARR\tPLAC", "{0:1}");
        m.put("MARR\tRELI", "{0:1}");
        m.put("MARR\tRESN", "{0:1}");
        m.put("MARR\tSDATE", "{0:1}");
        m.put("MARR\tSNOTE", "{0:M}");
        m.put("MARR\tSOUR", "{0:M}");
        m.put("MARR\tTYPE", "{0:1}");
        m.put("MARR\tUID", "{0:M}");
        m.put("MARR\tWIFE", "{0:1}");

        // ADDR cardinalities
        m.put("ADDR\tADR1", "{0:1}");
        m.put("ADDR\tADR2", "{0:1}");
        m.put("ADDR\tADR3", "{0:1}");
        m.put("ADDR\tCITY", "{0:1}");
        m.put("ADDR\tCTRY", "{0:1}");
        m.put("ADDR\tPOST", "{0:1}");
        m.put("ADDR\tSTAE", "{0:1}");

        // PLAC cardinalities
        m.put("PLAC\tEXID", "{0:M}");
        m.put("PLAC\tPLAC-FORM", "{0:1}");
        m.put("PLAC\tLANG", "{0:1}");
        m.put("PLAC\tMAP", "{0:1}");
        m.put("PLAC\tNOTE", "{0:M}");
        m.put("PLAC\tSNOTE", "{0:M}");
        m.put("PLAC\tPLAC-TRAN", "{0:M}");

        // MAP cardinalities
        m.put("MAP\tLATI", "{1:1}");
        m.put("MAP\tLONG", "{1:1}");

        // DATE cardinalities
        m.put("DATE\tPHRASE", "{0:1}");
        m.put("DATE\tTIME", "{0:1}");

        // SOUR (citation) cardinalities
        m.put("SOUR\tSOUR-DATA", "{0:1}");
        m.put("SOUR\tSOUR-EVEN", "{0:1}");
        m.put("SOUR\tNOTE", "{0:M}");
        m.put("SOUR\tOBJE", "{0:M}");
        m.put("SOUR\tPAGE", "{0:1}");
        m.put("SOUR\tQUAY", "{0:1}");
        m.put("SOUR\tSNOTE", "{0:M}");

        // CHAN cardinalities
        m.put("CHAN\tDATE-exact", "{1:1}");
        m.put("CHAN\tNOTE", "{0:M}");
        m.put("CHAN\tSNOTE", "{0:M}");

        // CREA cardinalities
        m.put("CREA\tDATE-exact", "{1:1}");

        // FILE cardinalities
        m.put("FILE\tFORM", "{1:1}");
        m.put("FILE\tTITL", "{0:1}");
        m.put("FILE\tFILE-TRAN", "{0:M}");

        // FORM cardinalities
        m.put("FORM\tMEDI", "{0:1}");

        // REFN cardinalities
        m.put("REFN\tTYPE", "{0:1}");

        // REPO (citation) cardinalities
        m.put("REPO\tCALN", "{0:M}");
        m.put("REPO\tNOTE", "{0:M}");
        m.put("REPO\tSNOTE", "{0:M}");

        // ASSO cardinalities
        m.put("ASSO\tNOTE", "{0:M}");
        m.put("ASSO\tPHRASE", "{0:1}");
        m.put("ASSO\tROLE", "{1:1}");
        m.put("ASSO\tSNOTE", "{0:M}");
        m.put("ASSO\tSOUR", "{0:M}");

        // FAMS cardinalities
        m.put("FAMS\tNOTE", "{0:M}");
        m.put("FAMS\tSNOTE", "{0:M}");

        // INDI-FAMC cardinalities
        m.put("INDI-FAMC\tNOTE", "{0:M}");
        m.put("INDI-FAMC\tPEDI", "{0:1}");
        m.put("INDI-FAMC\tSNOTE", "{0:M}");
        m.put("INDI-FAMC\tFAMC-STAT", "{0:1}");

        // NOTE cardinalities
        m.put("NOTE\tLANG", "{0:1}");
        m.put("NOTE\tMIME", "{0:1}");
        m.put("NOTE\tSOUR", "{0:M}");
        m.put("NOTE\tNOTE-TRAN", "{0:M}");

        // NO cardinalities
        m.put("NO\tNO-DATE", "{0:1}");
        m.put("NO\tNOTE", "{0:M}");
        m.put("NO\tSNOTE", "{0:M}");
        m.put("NO\tSOUR", "{0:M}");

        // FAM-HUSB / FAM-WIFE cardinalities
        m.put("FAM-HUSB\tPHRASE", "{0:1}");
        m.put("FAM-WIFE\tPHRASE", "{0:1}");

        // HEAD-DATE cardinalities
        m.put("HEAD-DATE\tTIME", "{0:1}");

        // HEAD-SOUR-DATA cardinalities
        m.put("HEAD-SOUR-DATA\tCOPR", "{0:1}");
        m.put("HEAD-SOUR-DATA\tDATE-exact", "{0:1}");

        // HEAD-PLAC cardinalities
        m.put("HEAD-PLAC\tHEAD-PLAC-FORM", "{1:1}");

        // SCHMA cardinalities
        m.put("SCHMA\tTAG", "{0:M}");

        // EXID cardinalities
        m.put("EXID\tEXID-TYPE", "{0:1}");

        // ADOP-FAMC cardinalities
        m.put("ADOP-FAMC\tFAMC-ADOP", "{0:1}");

        CARD_LOOKUP = Collections.unmodifiableMap(m);
    }

    // ─── Record tag -> context ID mapping ───────────────────────

    private static final Map<String, String> RECORD_CONTEXT;
    static {
        Map<String, String> m = new HashMap<>(16);
        m.put("INDI", "record-INDI");
        m.put("FAM", "record-FAM");
        m.put("OBJE", "record-OBJE");
        m.put("REPO", "record-REPO");
        m.put("SNOTE", "record-SNOTE");
        m.put("SOUR", "record-SOUR");
        m.put("SUBM", "record-SUBM");
        m.put("HEAD", "HEAD");
        RECORD_CONTEXT = Collections.unmodifiableMap(m);
    }

    /**
     * Resolves a (parentContextId, childTag) pair to the child structure ID.
     *
     * @param parentContextId the parent structure context (e.g. "record-INDI", "BIRT")
     * @param tag the child tag as it appears in the GEDCOM file
     * @return the child structure ID, or null if not found
     */
    public static String resolveStructure(String parentContextId, String tag) {
        return SUB_LOOKUP.get(parentContextId + "\t" + tag);
    }

    /**
     * Returns the cardinality for a (parentContextId, childStructureId) pair.
     *
     * @param parentContextId the parent structure context
     * @param childStructureId the resolved child structure ID
     * @return the cardinality string (e.g. "{0:1}", "{0:M}"), or null if not found
     */
    public static String getCardinality(String parentContextId, String childStructureId) {
        return CARD_LOOKUP.get(parentContextId + "\t" + childStructureId);
    }

    /**
     * Maps a level-0 record tag to its context ID.
     *
     * @param recordTag the record tag (e.g. "INDI", "FAM")
     * @return the context ID (e.g. "record-INDI"), or null if unknown
     */
    public static String recordContext(String recordTag) {
        return RECORD_CONTEXT.get(recordTag);
    }

    /**
     * Returns true if the cardinality limits the structure to at most one occurrence.
     *
     * @param cardinality the cardinality string (e.g. "{0:1}", "{1:1}")
     * @return true if max is 1
     */
    public static boolean isSingleton(String cardinality) {
        return cardinality != null
                && (cardinality.equals("{0:1}") || cardinality.equals("{1:1}"));
    }
}
