package org.gedcom7.writer;

import org.junit.jupiter.api.Test;

import java.io.ByteArrayOutputStream;
import java.nio.charset.StandardCharsets;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Tests for automatic HEAD.CHAR emission in GEDCOM 5.5.5 mode.
 */
class HeadCharTest {

    @Test
    void gedcom555ExplicitHeadIncludesCharUtf8() throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (GedcomWriter writer = new GedcomWriter(out, GedcomWriterConfig.gedcom555())) {
            writer.head(head -> head.source("Test"));
            writer.trailer();
        }
        String output = out.toString(StandardCharsets.UTF_8.name());
        assertTrue(output.contains("1 CHAR UTF-8"),
                "GEDCOM 5.5.5 HEAD should contain '1 CHAR UTF-8', got:\n" + output);
        // CHAR should appear after the GEDC/VERS block
        int versPos = output.indexOf("2 VERS 5.5.5");
        int charPos = output.indexOf("1 CHAR UTF-8");
        assertTrue(versPos >= 0, "Should contain VERS line");
        assertTrue(charPos > versPos, "CHAR should appear after VERS");
    }

    @Test
    void gedcom7ExplicitHeadDoesNotIncludeChar() throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        try (GedcomWriter writer = new GedcomWriter(out, GedcomWriterConfig.gedcom7())) {
            writer.head(head -> head.source("Test"));
            writer.trailer();
        }
        String output = out.toString(StandardCharsets.UTF_8.name());
        assertFalse(output.contains("CHAR"),
                "GEDCOM 7 HEAD should not contain CHAR line, got:\n" + output);
    }

    @Test
    void gedcom555AutoGeneratedHeadIncludesCharUtf8() throws Exception {
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        GedcomWriterConfig config = GedcomWriterConfig.gedcom555().toBuilder()
                .warningHandler(w -> {}) // suppress auto-head warning
                .build();
        try (GedcomWriter writer = new GedcomWriter(out, config)) {
            // Do not call head() explicitly; close() should auto-generate HEAD
            writer.trailer();
        }
        String output = out.toString(StandardCharsets.UTF_8.name());
        assertTrue(output.contains("1 CHAR UTF-8"),
                "Auto-generated GEDCOM 5.5.5 HEAD should contain '1 CHAR UTF-8', got:\n" + output);
    }
}
